### ISSUE TITLE
error when using pnp in strict mode due to undeclared dependencies 

### ISSUE THREAD

**Issue by adrian-gierakowski** [Quramy/typescript-eslint-language-service#497]
for example:

```
Failed to load module 'typescript-eslint-language-service' from /home/adrian/code/test-project/node_modules: Error: typescript-eslint-language-service tried to access @typescript-eslint/scope-manager, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

This affects users of yarn 3 ([berry](https://github.com/yarnpkg/berry)) and https://pnpm.io when using [pnp](https://yarnpkg.com/features/pnp).

Here's a patch which I had to put in my `.yarnrc.yml` to make silence the errors, which shows the deps accessed by this module in an unsound manner:

```yaml
packageExtensions:
  typescript-eslint-language-service@*:
    dependencies:
      "@eslint/eslintrc": ^1.3.3
      "@typescript-eslint/scope-manager": "*"
      "@typescript-eslint/types": "*"
      "@typescript-eslint/typescript-estree": "5.41.0"
      "@typescript-eslint/visitor-keys": "*"
      globby: ^11.1.0
      is-glob: ^4.0.3
```

Note that I had to pin `@typescript-eslint/typescript-estree` to `5.41.0` since `5.42.0` introduced a [breaking change](https://github.com/typescript-eslint/typescript-eslint/commit/8ddcc9a767a0794b17e603a8b11af998154ad3cb#diff-f45f590afd2d985b9d7362d20c89c8472d7d38ff8123b106272a819f03627995L66-R67) which breaks `typescript-eslint-language-service`
